// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/files/delete": {
            "delete": {
                "description": "Delete a file from a vault",
                "tags": [
                    "files"
                ],
                "summary": "Delete a file",
                "parameters": [
                    {
                        "type": "string",
                        "description": "File ID",
                        "name": "file_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Vault ID",
                        "name": "vault_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/files/get": {
            "get": {
                "description": "Get file details with presigned URLs for image and thumbnail",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "files"
                ],
                "summary": "Get a file",
                "parameters": [
                    {
                        "type": "string",
                        "description": "File ID",
                        "name": "file_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Vault ID",
                        "name": "vault_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal.FileResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/files/upload": {
            "post": {
                "description": "Upload an image file to a vault (multipart/form-data)",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "files"
                ],
                "summary": "Upload a file",
                "parameters": [
                    {
                        "type": "file",
                        "description": "Image file",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Vault ID",
                        "name": "vault_id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Folder ID (optional)",
                        "name": "folder_id",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/internal.File"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/users": {
            "post": {
                "description": "Create a new user with name, email, phone, and password",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Create a new user",
                "parameters": [
                    {
                        "description": "User object",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal.User"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/internal.User"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/vaults": {
            "get": {
                "description": "Get all vaults belonging to a user with their files",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vaults"
                ],
                "summary": "List vaults",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "user_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal.VaultResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/vaults/create": {
            "post": {
                "description": "Create a new vault for a user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vaults"
                ],
                "summary": "Create a new vault",
                "parameters": [
                    {
                        "description": "Vault object",
                        "name": "vault",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal.Vault"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/internal.Vault"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/vaults/delete": {
            "delete": {
                "description": "Delete a vault by ID (user must own the vault)",
                "tags": [
                    "vaults"
                ],
                "summary": "Delete a vault",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Vault ID",
                        "name": "vault_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "user_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/vaults/get": {
            "get": {
                "description": "Get a specific vault by ID with its files",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vaults"
                ],
                "summary": "Get a vault",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Vault ID",
                        "name": "vault_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "user_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal.VaultResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/vaults/update": {
            "put": {
                "description": "Update vault details (name, type, etc.)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vaults"
                ],
                "summary": "Update a vault",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Vault ID",
                        "name": "vault_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "user_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "Update fields",
                        "name": "updates",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal.Vault"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "internal.File": {
            "description": "File information",
            "type": "object",
            "properties": {
                "date": {
                    "type": "string",
                    "example": "2024-01-01"
                },
                "folder_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "logs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal.SyncLog"
                    }
                },
                "minio_key": {
                    "type": "string",
                    "example": "vault-id/uuid/image.jpg"
                },
                "name": {
                    "type": "string",
                    "example": "image.jpg"
                },
                "size": {
                    "type": "integer",
                    "example": 1024
                },
                "thumbnail": {
                    "type": "string",
                    "example": "vault-id/uuid/thumb_image.jpg"
                },
                "time": {
                    "type": "string",
                    "example": "2024-01-01T00:00:00Z"
                },
                "type": {
                    "type": "string",
                    "example": "image/jpeg"
                },
                "vault": {
                    "$ref": "#/definitions/internal.Vault"
                },
                "vault_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                }
            }
        },
        "internal.FileResponse": {
            "description": "File response with presigned URLs for image and thumbnail",
            "type": "object",
            "properties": {
                "date": {
                    "type": "string",
                    "example": "2024-01-01"
                },
                "folder_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "image_url": {
                    "type": "string",
                    "example": "https://minio.example.com/presigned-url"
                },
                "logs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal.SyncLog"
                    }
                },
                "minio_key": {
                    "type": "string",
                    "example": "vault-id/uuid/image.jpg"
                },
                "name": {
                    "type": "string",
                    "example": "image.jpg"
                },
                "size": {
                    "type": "integer",
                    "example": 1024
                },
                "thumbnail": {
                    "type": "string",
                    "example": "vault-id/uuid/thumb_image.jpg"
                },
                "thumbnail_url": {
                    "type": "string",
                    "example": "https://minio.example.com/presigned-url"
                },
                "time": {
                    "type": "string",
                    "example": "2024-01-01T00:00:00Z"
                },
                "type": {
                    "type": "string",
                    "example": "image/jpeg"
                },
                "vault": {
                    "$ref": "#/definitions/internal.Vault"
                },
                "vault_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                }
            }
        },
        "internal.SyncLog": {
            "type": "object",
            "properties": {
                "action": {
                    "type": "string"
                },
                "file": {
                    "$ref": "#/definitions/internal.File"
                },
                "fileID": {
                    "type": "string"
                },
                "folderID": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "vault": {
                    "$ref": "#/definitions/internal.Vault"
                },
                "vaultID": {
                    "type": "string"
                }
            }
        },
        "internal.User": {
            "description": "User account information",
            "type": "object",
            "properties": {
                "created_timestamp": {
                    "type": "string",
                    "example": "2024-01-01T00:00:00Z"
                },
                "email": {
                    "type": "string",
                    "example": "john@example.com"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "name": {
                    "type": "string",
                    "example": "John Doe"
                },
                "password": {
                    "type": "string",
                    "example": "password123"
                },
                "phone": {
                    "type": "integer",
                    "example": 1234567890
                }
            }
        },
        "internal.Vault": {
            "description": "Vault information",
            "type": "object",
            "properties": {
                "created_timestamp": {
                    "type": "string",
                    "example": "2024-01-01T00:00:00Z"
                },
                "files": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal.File"
                    }
                },
                "id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "logs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal.SyncLog"
                    }
                },
                "name": {
                    "type": "string",
                    "example": "My Vault"
                },
                "type": {
                    "type": "string",
                    "example": "personal"
                },
                "user_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                }
            }
        },
        "internal.VaultResponse": {
            "description": "Vault response with associated files",
            "type": "object",
            "properties": {
                "created_timestamp": {
                    "type": "string",
                    "example": "2024-01-01T00:00:00Z"
                },
                "files": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal.FileResponse"
                    }
                },
                "id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "logs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal.SyncLog"
                    }
                },
                "name": {
                    "type": "string",
                    "example": "My Vault"
                },
                "type": {
                    "type": "string",
                    "example": "personal"
                },
                "user_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "Agam API",
	Description:      "This is the Agam API server for managing users, vaults, and files.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
